---
- name: Ad-hoc wireless cjdns mesh of Raspberry Pi's with automatic CouchDB replication
  hosts: all
  # accelerate: true
  sudo: true
  vars:
    # 2013-12-20-wheezy-raspbian.img
    # 2014-01-07-wheezy-raspbian.img
    rootfs_original_size: 2786648064

  tasks:
    - include: tasks/firstboot.yml
    - include: tasks/packages.yml
    - include: tasks/networking.yml
    # - include: tasks/cjdns.yml
    # - include: tasks/couchdb.yml
    # - include: tasks/ruby.yml

    # TODO announce, replicate
    # TODO make it safe
    # TODO make it fast
    # TODO make it pretty
