---
- hostname: name="{{ hostname }}"
- lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1' line="127.0.1.1 {{ hostname }}"

- script: files/raspi-expand-rootfs.sh
  when: rootfs_original_size == ansible_mounts[0].size_total
  register: expand_rootfs

- shell: dpkg --force-remove-essential -r sysvinit && apt-get install -y --force-yes upstart creates=/sbin/start
  register: install_upstart

- include: reboot.yml
  when: "expand_rootfs.changed or install_upstart.changed"
