---
- command: shutdown -r now
- local_action: wait_for host="{{ inventory_hostname }}" port=22 state=stopped
  sudo: false
- local_action: wait_for host="{{ inventory_hostname }}" port=22 state=started
  sudo: false
